---
- name: "restartApp"
  service: 
    name="{{ deployment_artifact_name }}"
    state="restarted"
    enabled="yes"
  notify: "wait for application to bootstrap"
  when: deployment_install_initd

- name: "wait for application to bootstrap"
  pause: seconds={{ deployment_bootstrap_wait_sec }}
  changed_when: true
  notify: "make http request to service"

- name: "make http request to service"
  uri: url={{deployment_http_check_url}} return_content=yes HEADER_Accept="text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
  register: webpage
  tags: ["verify-working"]
  notify: "fail if http request does not contain expected content"
  when: deployment_http_check_url_suffix is defined

- name: "fail if http request does not contain expected content"
  fail: msg=" {{deployment_artifact_name}} is not happy, {{deployment_http_check_url}} does not return expected content [{{deployment_http_check_expected_content}}]"
  when: "'{{deployment_http_check_expected_content}}' not in webpage.content"
  tags: ["verify-working"]


